#Server Start
MENU_NAMES["SERVSTART,TITLE"]="Server Start"
MENU_NAMES["SERVSTART,FUNC"]="Menu_Start_Servers"
MENU_NAMES["SERVSTART,OPTNUM"]=2

MENU_OPTIONS["SERVSTART,OPT1"]="Start New Server"
MENU_OPTIONS["SERVSTART,OPT2"]="Start New Set of Servers"