# declare -a SCREENLIST_ALL #all screen sessions
# SCREENLIST_ALL["ID"]=0
# SCREENLIST_ALL["SCREENS"]=0
# SCREENLIST_ALL["SERVERS"]=0
# declare -a SCREENLIST_ZANDRONUM #all zandronum screen sessions
# SCREENLIST_ZANDRONUM["ID"]=0
# SCREENLIST_ZANDRONUM["SCREENS"]=0
# SCREENLIST_ZANDRONUM["SERVERS"]=0

declare -A LISTOFSCREENS
LISTOFSCREENS["ALL,COUNT"]=0
LISTOFSCREENS["ALL,ID"]=0
LISTOFSCREENS["ALL,NAME"]="null"
LISTOFSCREENS["ALL,WINDOWCOUNT"]=0
LISTOFSCREENS["RAMPAGE,COUNT"]=0
LISTOFSCREENS["RAMPAGE,ID"]=0
LISTOFSCREENS["RAMPAGE,NAME"]="rampage"
LISTOFSCREENS["RAMPAGE,WINDOWCOUNT"]=0

declare -A SCREEN_INFO
SCREEN_INFO["ID,NAME"]="null"
SCREEN_INFO["ID,WINDOWCOUNT"]=0
SCREEN_INFO["ID,SERVERCOUNT"]=0